### ISSUE TITLE
Poisontap need help please

### ISSUE THREAD

**Issue by M1ndHunt3r007** [samyk/poisontap#133]
Dear,
I am trying to get Poisontap working on my Pi Zero.
I having problems with the backend_server...does any1 knows a good tut for this?
The last 2 days, I was busy searching the webabout this matter, but I cant find any good working tutorial.

Please help

Kind regards.
Natascha

Sorry for my poor English

**Comment by M1ndHunt3r007** [comment]
To bad, no help...

**Comment by samyk** [comment]
Did you try the example in the readme?

**Comment by M1ndHunt3r007** [comment]
Yes, i tried, but no luck.....for the backend serever; I did this:
https://nuxview.blogspot.nl/2016/11/poisontap-setting-up-backend.html
i tried to search on the net for a more detailed tutorial, but no luck...

**Comment by samyk** [comment]
I have no idea what issues you're running into because you've provided no information other than "no luck"

**Comment by M1ndHunt3r007** [comment]
![node](https://user-images.githubusercontent.com/34381719/33798218-a8bd3be2-dce2-11e7-8dec-e5e46f13f665.png)

**Comment by M1ndHunt3r007** [comment]
i dont know what I must change in the backdoor.html, I have 2 ip's from digital ocean...I dont know which Ip i must put in the backdoor.html

**Comment by samyk** [comment]
Are they both public IPs? If you're not sure, what are the IPs? The backend_server should listen to all IPs by default.

**Comment by M1ndHunt3r007** [comment]
![ip](https://user-images.githubusercontent.com/34381719/33798525-2f6cfccc-dce8-11e7-8c61-9d8817739fd7.png)

**Comment by M1ndHunt3r007** [comment]
Which files must i edit now?

**Comment by samyk** [comment]
Use 188.166.15.36 - change "YOUR.DOMAIN" in backdoor.html to the IP you want to use

**Comment by M1ndHunt3r007** [comment]
Thank you Samyk.

I will work on this matter.....I think i have 1 other issue....:
When I want to do this:
#DHCP: 
sudo cp -f dhcpd.conf /etc/dhcp/dhcpd.conf
add this to  /etc/default/isc-dhcp-server:
INTERFACES="usb0"   (>>>>>I got an error: Permission denied.)
===============


So, I will find out how to edit this...
thanks for helping

**Comment by M1ndHunt3r007** [comment]
Thank you Samyk.  
I will work on this matter.....I think i have 1 other issue....: When I want to do this: 
#DHCP:  
sudo cp -f dhcpd.conf /etc/dhcp/dhcpd.conf 
add this to  /etc/default/isc-dhcp-server: 
INTERFACES="usb0"   (>>>>>I got an error: Permission denied)

I will search the web for a solution..
Thnxz for helping

**Comment by M1ndHunt3r007** [comment]
This guy did it very good
https://www.youtube.com/watch?v=BSV-aEkAbNY

If some1 can make a tutorial, that is the same as in the video, I will pay him for his time.

Kind regards

**Comment by M1ndHunt3r007** [comment]
I got this error message, and I dont know how to fix it:



events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::1337
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1406:7)
    at Object.<anonymous> (/poisontap/backend_server.js:50:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
root@Poisontap:/poisontap#

**Comment by samyk** [comment]
Something else is running on port 1337 (possibly another instance of the backdoor). `lsof -n | grep 1337` should tell you what process and you can `kill -9` it

**Comment by M1ndHunt3r007** [comment]
Thnxz, that worked...server is listening on port 1337 now...
thnxz man...

**Comment by M1ndHunt3r007** [comment]
Does any1 knows how to host and setup the backend server on Amazon AWS?
Thnxz in advance
I am also willing to pay for the help

kind regards

**Comment by aidanbowler** [comment]
hi

**Comment by aidanbowler** [comment]
ip  number  for leighton buzzard
